version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50000:80
    volumes:
      - ./html:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: cs490db
      MYSQL_USER: dbdev
      MYSQL_PASSWORD: dbdevpass
      MYSQL_ROOT_PASSWORD: dontdothis
    volumes:
      - CS490sql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 50001:8080

volumes:
  CS490sql:
    external: true